function DataCenter(){
    this.aliveHumanList=new Array();
    this.deadHumanList=new Array();
    this.houseList=new Array();
    this.townList=new Array();
    this.logsList=new Array();
    this.census={"human":new Array(),"house":new Array()};
    this.age=0;
    this.townsNumber=10;
}

DataCenter.prototype.getTown= function(id){
    let town=dc.townList.filter(function(ele){ return ele.id == id; })[0];
    if(town==undefined){return "";}
    return town;
}
DataCenter.prototype.richest= function(town){
    let towns=dc.houseList.filter(function(ele){ return ele.town == town.id; });
    return towns.reduce((accumulator, currentValue) => {
        return (accumulator.gold > currentValue.gold ? accumulator : currentValue);},{gold:-100});
}
DataCenter.prototype.TOWN_NAME_LIST = ['Paris',    'Marseille',    'Lyon',    'Nice',    'Lille',    'Rennes',    'Nantes',    'Angers',    'Strasbourg',    'Poitiers',    'Angouleme',    'Grenoble',    'Amiens',    'Rouen',    'Caen',    'Bordeau',    'Pau',    'Montpellier',    'Narbonne',    'Orange',    'Avignon',    'Limoges'];


DataCenter.prototype.SURNAME_LIST = ['Martin',
'Bernard',
'Thomas',
'Petit',
'Robert',
'Richard',
'Durand',
'Dubois',
'Moreau',
'Laurent',
'Simon',
'Michel',
'Lefebvre',
'Leroy',
'Roux',
'David',
'Bertrand',
'Morel',
'Fournier',
'Girard',
'Bonnet',
'Dupont',
'Lambert',
'Fontaine',
'Rousseau',
'Vincent',
'Muller',
'Lefevre',
'Faure',
'Andre',
'Mercier',
'Blanc',
'Guerin',
'Boyer',
'Garnier',
'Chevalier',
'Francois',
'Legrand',
'Gauthier',
'Garcia',
'Perrin',
'Robin',
'Clement',
'Morin',
'Nicolas',
'Henry',
'Roussel',
'Mathieu',
'Gautier',
'Masson',
'Marchand',
'Duval',
'Denis',
'Dumont',
'Marie',
'Lemaire',
'Noel',
'Meyer',
'Dufour',
'Meunier',
'Brun',
'Blanchard',
'Giraud',
'Joly',
'Riviere',
'Lucas',
'Brunet',
'Gaillard',
'Barbier',
'Arnaud',
'Martinez',
'Gerard',
'Roche',
'Renard',
'Schmitt',
'Roy',
'Leroux',
'Colin',
'Vidal',
'Caron',
'Picard',
'Roger',
'Fabre',
'Aubert',
'Lemoine',
'Renaud',
'Dumas',
'Lacroix',
'Olivier',
'Philippe',
'Bourgeois',
'Pierre',
'Benoit',
'Rey',
'Leclerc',
'Payet',
'Rolland',
'Leclercq',
'Guillaume',
'Lecomte',
'Lopez',
'Jean',
'Dupuy',
'Guillot',
'Hubert',
'Berger',
'Carpentier',
'Sanchez',
'Dupuis',
'Moulin',
'Louis',
'Deschamps',
'Huet',
'Vasseur',
'Perez',
'Boucher',
'Fleury',
'Royer',
'Klein',
'Jacquet',
'Adam',
'Paris',
'Poirier',
'Marty',
'Aubry',
'Guyot',
'Carre',
'Charles',
'Renault',
'Charpentier',
'Menard',
'Maillard',
'Baron',
'Bertin',
'Bailly',
'Herve',
'Schneider',
'Fernandez',
'Le Gall',
'Allard',
'Le Calvé',
'Labouret',
'Corneggia',
'Collet',
'Leger',
'Bouvier',
'Julien',
'Prevost',
'Millet',
'Perrot',
'Daniel',
'Le Roux',
'Cousin',
'Germain',
'Breton',
'Besson',
'Langlois',
'Remy',
'Le Goff',
'Pelletier',
'Leveque',
'Perrier',
'Leblanc',
'Barre',
'Lebrun',
'Marchal',
'Weber',
'Mallet',
'Hamon',
'Boulanger',
'Jacob',
'Monnier',
'Michaud',
'Rodriguez',
'Guichard',
'Gillet',
'Etienne',
'Grondin',
'Poulain',
'Tessier',
'Chevallier',
'Collin',
'Chauvin',
 'Da Silva',
'Bouchet',
'Gay',
'Lemaitre',
'Benard',
'Marechal',
'Humbert',
'Reynaud',
'Antoine',
'Hoarau',
'Perret',
'Barthelemy',
'Cordier',
'Pichon',
'Lejeune',
'Gilbert',
'Lamy',
'Delaunay',
'Pasquier',
'Carlier',
'Laporte'];
DataCenter.prototype.FEMALE_NAME_LIST = ['Emma',    'Jade',    'Louise',    'Alice',    'Chloé',    'Lina',    'Léa',    'Rose',    'Anna',    'Mila',    'Inès',    'Ambre',    'Julia',    'Mia',    'Léna',    'Manon',    'Juliette',    'Lou',    'Camille',    'Zoé',    'Lola',    'Agathe',    'Jeanne',    'Lucie',    'Éva',    'Nina',    'Sarah',    'Romane',    'Inaya',    'Charlotte',    'Léonie',    'Romy',    'Adèle',    'Iris',    'Louna',    'Sofia',    'Margaux',    'Luna',    'Olivia',    'Clémence',    'Victoria',    'Léana',    'Clara',    'Éléna',    'Victoire',    'Aya',    'Margot',    'Nour',    'Giulia',    'Charlie',    'Capucine',    'Mya',    'Mathilde',    'Lana',    'Anaïs',    'Lilou',    'Alicia',    'Théa',    'Gabrielle',    'Lya',    'Yasmine',    'Maëlys',    'Assia',    'Apolline',    'Élise',    'Alix',    'Emy',    'Lise',    'Elsa',    'Lily',    'Lyana',    'Lisa',    'Noémie',    'Marie',    'Roxane',    'Lyna',    'Héloïse',    'Candice',    'Valentine',    'Zélie',    'Maya',    'Soline',    'Maria',    'Célia',    'Maëlle',    'Emmy',    'Éléna',    'Faustine',    'Salomé',    'Lila',    'Louane',    'Alya',    'Thaïs',    'Constance',    'Laura',    'Mélina',    'Livia',    'Amelia',    'Océane',    'Sara']
DataCenter.prototype.MALE_NAME_LIST = ['Gabriel',    'Raphaël',    'Léo',    'Louis',    'Lucas',    'Adam',    'Arthur',    'Jules',    'Hugo',    'Maël',    'Liam',    'Ethan',    'Paul',    'Nathan',    'Gabin',    'Sacha',    'Noah',    'Tom',    'Mohamed',    'Aaron',    'Théo',    'Noé',    'Victor',    'Martin',    'Mathis',    'Timéo',    'Nolan',    'Enzo',    'Éden',    'Axel',    'Antoine',    'Léon',    'Marius',    'Robin',    'Valentin',    'Clément',    'Baptiste',    'Tiago',    'Rayan',    'Samuel',    'Amir',    'Augustin',    'Naël',    'Maxime',    'Maxence',    'Gaspard',    'Eliott',    'Alexandre',    'Isaac',    'Mathéo',    'Yanis',    'Évan',    'Simon',    'Malo',    'Nino',    'Marceau',    'Kylian',    'Thomas',    'Ibrahim',    'Imran',    'Ayden',    'Lenny',    'Camille',    'Lyam',    'Kaïs',    'Oscar',    'Naïm',    'Sohan',    'Côme',    'Milo',    'Noa',    'Ilyes',    'Noam',    'Diego',    'Ismaël',    'Léandre',    'Soan',    'Mathys',    'Alexis',    'Lorenzo',    'Esteban',    'Owen',    'Youssef',    'Ilyan',    'William',    'Adrien',    'Ayoub',    'Jean',    'David',    'Ali',    'Adem',    'Wassim',    'Logan',    'Sandro',    'Pablo',    'Antonin',    'Joseph',    'Benjamin',    'Noham',    'Kenzo'];